name: Test and Publish

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          version: 3.6
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
          pip install pytest
          pip install pytest-cov
      - name: Code style check
        run: flake8 srdatasets/ tests/
      - name: Generate coverage report
        run: |
          export PYTHONPATH="."
          pytest --cov=srdatasets --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: codecov-umbrella
  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Build
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
